# NumPy

In [1]:
import numpy as np

## NumPy Ndarray对象

```python
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```

* object：数列或嵌套数列
* dtype：数据类型
* copy：对象是否需要复制
* order：创建数组的样式（C：行方向；F：列方向；A：任意方向（默认））
* subok：返回一个与基类类型相同的数组
* ndmin：指定最小维度

In [3]:
# 多于一个维度  
import numpy as np 
a = np.array([[1,  2],  [3,  4]])  
print (a)

[[1 2]
 [3 4]]


In [4]:
import numpy as np 
a = np.array([1,  2,  3,4,5], ndmin =  2)  
print (a)

[[1 2 3 4 5]]


```python
numpy.dtype(object, align, copy)
```

In [6]:
import numpy as np
# int8, int16, int32, int64 四种数据类型可以使用字符串 'i1', 'i2','i4','i8' 代替
dt = np.dtype('i4')
print(dt)

import numpy as np # 类似于结构体（S20 name; i1 age; f4 marks;）
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) # name = 'abc', age = 21, marks = 50 
print(a)

int32
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


| 属性 | 说明 |
| :-----: | :-----: |
| ndarray.ndim | 秩/维度 |
| ndarray.shape | n行m列 |
| ndarray.size | 元素总数（n\*m） |
| ndarray.dtype | 元素的类型 |

很多时候可以声明 axis。axis=0，表示沿着第 0 轴进行操作，即对每一列进行操作；axis=1，表示沿着第1轴进行操作，即对每一行进行操作。

In [8]:
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape) # shape

a = np.array([[1,2,3],[4,5,6]]) 
a.shape =  (3,2)  # 调整shape，变成3行2列
print (a)

a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2)  # 同上
print (b)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


## Numpy创建数组
```python
numpy.empty(shape, dtype = float, order = 'C') # 创建空数组
numpy.zeros(shape, dtype = float, order = 'C') # 创建用0填充的数组
numpy.ones(shape, dtype = None, order = 'C')  # 创建用1填充的数组
numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0) # 以流的形式读入转化成ndarray对象（需要指定对象类型）
numpy.fromiter(iterable, dtype, count=-1) # 从可迭代对象中建立 ndarray 对象，返回一维数组
numpy.arange(start, stop, step, dtype) # 创建数值范围并返回 ndarray 对象
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None) # 生成等差数组
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None) # 生成等比数组
```

*注意：buffer 是字符串的时候，Python3 默认 str 是 Unicode 类型，所以要转成 bytestring 在原 str 前加上 b。*

In [10]:
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  # 注意数据类型；只能生成数组
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [11]:
# 使用 range 函数创建列表对象  
list=range(5)
it=iter(list)
# 使用迭代器创建 ndarray 
x=np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [16]:
x = np.arange(10,20,2) # 范围依次生成数组[start: end: step] 
print (x)
print()

a = np.linspace(1,10,10).reshape([10,1]) # 生成等差数组（与上面类似）
print(a)
print()

a = np.logspace(0,9,10,base=2) # 生成等比数组（从下标0和9中输出10个数）
print (a)
print()

# 默认底数是 10
a = np.logspace(1.0,  2.0, num =  10)  # 生成等比数组（从下标1和2中输出10个数）
print (a)

[10 12 14 16 18]

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


## NumPy 切片和索引

In [17]:
a = np.arange(10)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])
print()

b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)

[2 4 6]

[2 4 6]


In [18]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) # 用省略号表示
print (a[...,1])   # 第2列元素
print (a[1,...])   # 第2行元素
print (a[...,1:])  # 第2列及剩下的所有元素

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [19]:
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
y = x[[0,1,2],  [0,1,0]]  # 获取数组中(0,0)，(1,1)和(2,0)位置处的元素
print (y)
print()

x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])
print  ('大于 5 的元素是：')
print (x[x > 5]) # 布尔索引

[1 4 5]

大于 5 的元素是：
[ 6  7  8  9 10 11]


In [20]:
a = np.array([np.nan,  1,2,np.nan,3,4,5])  
print (a[~np.isnan(a)])  # 过滤NaN

a = np.array([1,  2+6j,  5,  3.5+5j])  
print (a[np.iscomplex(a)]) # 过滤非复数元素

[1. 2. 3. 4. 5.]
[2. +6.j 3.5+5.j]


In [21]:
x=np.arange(32).reshape((8,4)) # 花式切片：对应行的下标下标
print (x[[-4,-2,-1,-7]])

[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]


## NumPy 广播(Broadcast) 

广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式， 对数组的算术运算通常在**相应的元素**上进行。  
如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，那么 a\*b 的结果就是 a 与 b 数组**对应位相乘**。这要求维数相同，且各维度的长度相同。

![jupyter](./broadcast.gif)

In [23]:
a = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([1, 2, 3])  # 其中一维为1，自动扩充
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


广播的规则：
* 数组拥有相同形状。
* 当前维度的值相等。
* 当前维度的值有一个是 1。
* 让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加 1 补齐。

## NumPy 迭代数组

In [24]:
a = np.arange(6).reshape(2,3)
print ('原始数组是：')
print (a)
print ('\n')
print ('迭代输出元素：')
for x in np.nditer(a): # 将数组迭代
    print (x, end=", " )
print ('\n')

原始数组是：
[[0 1 2]
 [3 4 5]]


迭代输出元素：
0, 1, 2, 3, 4, 5, 



In [25]:
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print  ('第一个数组为：')
print (a)
print  ('\n')
print ('第二个数组为：')
b = np.array([1,  2,  3,  4], dtype =  int)  
print (b)
print ('\n')
print ('修改后的数组为：')
for x,y in np.nditer([a,b]):  # 若两个数组可广播，则可同时迭代
    print ("(%d:%d)"  %  (x,y), end=", " )

第一个数组为：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


第二个数组为：
[1 2 3 4]


修改后的数组为：
(0:1), (5:2), (10:3), (15:4), (20:1), (25:2), (30:3), (35:4), (40:1), (45:2), (50:3), (55:4), 

## 数组操作
* 修改数组形状
* 翻转数组
* 修改数组维度
* 连接与分割数组
* 数组元素的添加与删除  
具体操作请点击[数组操作详解](https://www.runoob.com/numpy/numpy-array-manipulation.html#numpy_oparr1)

## NumPy 数学函数

* 三角函数：np.sin(), np.arcsin(), np.degrees()（弧度->角度）
* 舍入函数：np.around(a, decimals)（四舍五入）, np.floor(), np.ceil()
* 算数函数：np.add(), np.substract(), np.multiply(), np.divide(), np.reciprocal()（返回倒数）, np.power(), np.mod()（符合广播规则）, np.exp()（以e为底）, np.sqrt(), np.power()
* 统计函数：np.amin(a, 0), np.amax(), np.ptp()（极差）, np.percentile(a, q, axis)（百分位数，q=50时为中位数）, np.median()（中位数）, np.mean(a, axis=0), np.average(a, weight=[1]), np.std()（标准差）, np.var()（方差）
* 特殊值：np.pi

### 线性代数
* np.dot()：两个数组点积
* np.vdot()：两个向量点积（若高维则展开）
* np.inner()：两个数组的内积